PREFIX escjr: <http://vocab.linkeddata.es/datosabiertos/def/urbanismo­infraestructuras/callejero#>
PREFIX esadm: <http://vocab.linkeddata.es/datosabiertos/def/sector­publico/territorio#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT DISTINCT ?via ?barrio ?fechaCreacion WHERE{
	?via a escjr:Via .
	?via dcterms:date ?fechaCreacion .
	?via esadm:barrio ?barrio
} ORDER BY DESC(?fechaCreacion)

#Results
#Number of results
 >1
#Type of the results
Literal, Literal, Literal
#List of results

