PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?label
WHERE {
   {
      
      <http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/callejero#TramoVia>  rdfs:subClassOf ?superC .
      ?superC ?prop1  ?label
      
   }UNION{
     <http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/callejero#TramoVia>    ?prop2  ?label
   } UNION {
   
      <http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/callejero#Via>  rdfs:subClassOf ?superC .
      ?superC ?prop1  ?label
   }UNION {
      <http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/callejero#TramoVia>    ?prop2  ?label
   }
   
   
   
 }
#Results
#Number of results
 >1
#Type of the results
Literal
#List of results
