PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?y1 ?y2
WHERE{
	{
	<http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/callejero#Via> ?x1 ?y1 . 
	 FILTER regex(str(?label), "año", "i")
	}UNION{<http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/callejero#Via> ?x2 ?y2 . 
	 FILTER regex(str(?label), "barrio", "i")}

}

#Results
#Number of results
 1
#Type of the results
Boolean
#List of results
true
