PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?label1 ?label2
WHERE {
   {
      ?label1 ?prop1 <http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/callejero#TramoVia>
   }UNION{
     ?label2 ?prop2  <http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/callejero#Via>  
   }
 }
#Results
#Number of results
 >1
#Type of the results
Literal
#List of results

