PREFIX escjr: <http://vocab.linkeddata.es/datosabiertos/def/urbanismo­infraestructuras/callejero#>

SELECT DISTINCT ?viaTramo WHERE{

{?viaTramo a escjr:Via} UNION {?viaTramo a escjr:TramoVia}

}
#Results
#Number of results
 >1
#Type of the results
Literal
#List of results

