PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?x1 ?x2
WHERE{
	{
 	 ?x1 ?y1 <http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/callejero#Via> . 
 	 FILTER regex(str(?y1), "año", "i")
 	}UNION{ ?x2 ?y2 <http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/callejero#Via> . 
 	 FILTER regex(str(?y2), "barrio", "i")}

 }

#Results
#Number of results
 >1
#Type of the results
Literal, Literal, Literal
#List of results

