PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>


SELECT ?prop ?label
WHERE {

   ?prop ?label  <http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/callejero#TramoVia>  .
}

#Results
#Number of results
 >1
#Type of the results
Literal
#List of results
http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/callejero#numeroInicioTramo
