PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

ASK{
{
      <http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/callejero#TramoVia>  rdfs:subClassOf ?superC .
      ?label  ?prop ?superC  .
      FILTER regex(str(?label), "afluencia", "i")
   } UNION{
      ?label  ?prop  <http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/callejero#TramoVia> .
      FILTER regex(str(?label), "afluencia", "i")
  }
}

#Results
#Number of results
 >0
#Type of the results
Number
#List of results
False
   
   
   
 
