PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT   ?label ?class
WHERE { 
        <http://vocab.linkeddata.es/datosabiertos/def/turismo/lugar#Itinerario> rdfs:label ?label .
        <http://vocab.linkeddata.es/datosabiertos/def/turismo/lugar#Itinerario> rdfs:subClassOf ?class
        
     } 

#Results
#Number of results
 > 1
#Type of the results
Literal, URIRef
#List of results
itinerario, http://schema.org/TouristAttraction
