
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT   ?super
WHERE { 
        <http://vocab.linkeddata.es/datosabiertos/def/turismo/lugar#ZonaTuristica>  rdfs:subClassOf  ?super
       ?super rdfs:domain ?super  .
       
       
       
     } 

#Results
#Number of results
 > 1
#Type of the results
Literal
#List of results
afluencia de p\xc3\xbablico
#Priority
1
