PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT   ?subclass ?label
WHERE { 
        ?subclass rdfs:label ?label
     } 

#Results
#Number of results
 > 1
#Type of the results
literal
#List of results
poblacion
#Priority
1
