
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT  ?subclass ?prop ?value
WHERE { 
        <http://vocab.linkeddata.es/datosabiertos/def/turismo/lugar#ZonaTuristica> ?prop ?value
        ?subclass rdfs:subClassOf <http://vocab.linkeddata.es/datosabiertos/def/turismo/lugar#ZonaTuristica>
     } 

#Results
#Number of results
 > 5
#Type of the results
uri, literal, literal, literal
#List of results
http://www.w3.org/2001/XMLSchema#anyURI, xsd:anyURI, xsd:anyURI, xsd:anyURI
#Priority
1
