PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?class 
WHERE { ?class rdfs:label "Lugar de Interés Turístico".
        ?subclass rdfs:subClassOf ?class 

} 

#Results
#Number of results
 5
#Type of the results
uri, number
#List of results
http://www.w3.org/2001/XMLSchema#anyURI, xsd:anyURI
#Priority
1
