PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
ASK  { ?x <http://www.w3.org/2002/07/owl#ObjectProperty>  ?y }
#Results
#Number of results
 1
#Type of the results
boolean
#List of results
true
#Priority
1
