PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?x ?label
WHERE {
   ?x rdfs:label ?label .
   FILTER regex(str(?label), "accesible", "i")
}

#Results
#Number of results
 1
#Type of the results
boolean
#List of results
poblacion
#Priority
1
