PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

ASK {

   <http://vocab.linkeddata.es/datosabiertos/def/sector-publico/territorio#Barrio> ?prop ?label .
   FILTER regex(str(?label), "poblacion", "i")

}


#Results
#Number of results
 1
#Type of the results
Boolean
#List of results
true
